Repository json-schema-org/json-schema-spec, pull requests merged in 2020-05, with the labels that each got.

#915 Placeholder changelog
  jsonschema-core.xml
  jsonschema-validation.xml
Labels: administrative

#929 Ether/minor wording
  jsonschema-core.xml
  jsonschema-validation.xml
Labels: Type: Bug, core

#931 Update years on core and hyperschema
  jsonschema-core.xml
  jsonschema-hyperschema.xml
Labels: administrative

#917 contentSchema: type MUST be a schema
  jsonschema-validation.xml
Labels: annotation

#925 Split "prefixItems" from "items", drop "additionalItems", make "unevaluatedItems" respect "contains"
  jsonschema-core.xml
  meta/applicator.json
Labels: core
